[target.riscv32imac-unknown-none-elf]
runner = [
    "cargo",
    "-Z",
    "unstable-options",
    "-C",
    "tools/device-runner",
    "run",
    "--quiet",
    "--target",
    "host-tuple",
    "--",
]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
  "-Z", "stack-protector=all",
]

[env]
DEFMT_LOG="info"

[build]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
